version: '3.4'

services:
  broker:
    image: mosquitto
    restart: always
    build:
      context: mosquitto
      dockerfile: ./Dockerfile
  orangebox:
    image: orangebox
    restart: always
    build:
      context: orangebox
      dockerfile: ./Dockerfile
    volumes:
      - /var/local/groundstation:/data:rw
  deejay:
    image: deejay
    restart: always
    build:
      context: deejay
      dockerfile: ./Dockerfile
    volumes:
      - /var/local/groundstation:/data:rw
    ports:
      - "8080:8080"
  gateway:
    image: gateway
    restart: always
    build:
      context: gateway
      dockerfile: ./Dockerfile
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
