version: '3.4'

services:
  broker:
    image: mosquitto
    restart: always
    build:
      context: mosquitto
      dockerfile: ./Dockerfile
  orangebox:
    image: orangebox
    restart: always
    build:
      context: orangebox
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/data:rw
    stop_signal: SIGINT
  deejay:
    image: deejay
    restart: always
    build:
      context: deejay
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/data:rw
    ports:
      - "8080:8080"
    stop_signal: SIGINT
  gateway:
    image: gateway-udp
    restart: always
    build:
      context: gateway
      dockerfile: ./Dockerfile
      args:
        SENSORNET: udp
    ports:
      - "10000:10000/udp"
    stop_signal: SIGINT
